#!/bin/sh
set -eu

APP_DIR="/CLIProxyAPI"
DATA_ROOT="${CLIPROXY_DATA_ROOT:-/data}"
AUTH_DIR="${CLIPROXY_AUTH_DIR:-$DATA_ROOT/auths}"
CONFIG_DIR="${CLIPROXY_CONFIG_DIR:-$AUTH_DIR/.config}"
CONFIG_PATH="${CLIPROXY_CONFIG_PATH:-$CONFIG_DIR/config.yaml}"
PORT_VALUE="${PORT:-${CLIPROXY_PORT:-8317}}"

API_KEYS_VALUE="${CLIPROXY_API_KEYS:-${API_KEYS:-}}"
MGMT_KEY_VALUE="${CLIPROXY_MGMT_KEY:-}"
ALLOW_REMOTE_MANAGEMENT="${CLIPROXY_ALLOW_REMOTE_MANAGEMENT:-true}"
REQUEST_RETRY_VALUE="${CLIPROXY_REQUEST_RETRY:-3}"
SWITCH_PROJECT_VALUE="${CLIPROXY_SWITCH_PROJECT:-true}"
SWITCH_PREVIEW_MODEL_VALUE="${CLIPROXY_SWITCH_PREVIEW_MODEL:-false}"
ROUTING_STRATEGY_VALUE="${CLIPROXY_ROUTING_STRATEGY:-round-robin}"
DEBUG_VALUE="${CLIPROXY_DEBUG:-false}"
AUTO_IMPORT_TOKENS="${CLIPROXY_AUTO_IMPORT_TOKENS:-true}"
IMPORT_MIN_EXISTING="${CLIPROXY_IMPORT_MIN_EXISTING:-5}"
ZHUCEJI_URL="${ZHUCEJI_URL:-https://codex-zhuceji.up.railway.app}"
SKIP_EXEC="${CLIPROXY_SKIP_EXEC:-false}"

mkdir -p "$CONFIG_DIR" "$AUTH_DIR"

is_truthy() {
    case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
        1|true|yes|on) return 0 ;;
        *) return 1 ;;
    esac
}

render_initial_config() {
    export CONFIG_PATH AUTH_DIR PORT_VALUE API_KEYS_VALUE MGMT_KEY_VALUE
    export ALLOW_REMOTE_MANAGEMENT REQUEST_RETRY_VALUE SWITCH_PROJECT_VALUE
    export SWITCH_PREVIEW_MODEL_VALUE ROUTING_STRATEGY_VALUE DEBUG_VALUE
    python3 - <<'PY'
import json
import os
import sys


def parse_bool(value: str) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def parse_api_keys(value: str):
    normalized = value.replace("\n", ",")
    return [item.strip() for item in normalized.split(",") if item.strip()]


config_path = os.environ["CONFIG_PATH"]
auth_dir = os.environ["AUTH_DIR"]
port = os.environ["PORT_VALUE"]
api_keys = parse_api_keys(os.environ.get("API_KEYS_VALUE", ""))
mgmt_key = os.environ.get("MGMT_KEY_VALUE", "").strip()

if not api_keys:
    sys.stderr.write(
        "entrypoint.railway: missing CLIPROXY_API_KEYS or API_KEYS for first boot\n"
    )
    sys.exit(1)

if not mgmt_key:
    sys.stderr.write(
        "entrypoint.railway: missing CLIPROXY_MGMT_KEY for first boot\n"
    )
    sys.exit(1)

allow_remote = parse_bool(os.environ.get("ALLOW_REMOTE_MANAGEMENT", "true"))
request_retry = int(os.environ.get("REQUEST_RETRY_VALUE", "3"))
switch_project = parse_bool(os.environ.get("SWITCH_PROJECT_VALUE", "true"))
switch_preview_model = parse_bool(
    os.environ.get("SWITCH_PREVIEW_MODEL_VALUE", "false")
)
debug_enabled = parse_bool(os.environ.get("DEBUG_VALUE", "false"))
routing_strategy = os.environ.get("ROUTING_STRATEGY_VALUE", "round-robin").strip()
if not routing_strategy:
    routing_strategy = "round-robin"

lines = [
    "# Generated by entrypoint.railway.sh on first boot.",
    f"port: {int(port)}",
    f"auth-dir: {json.dumps(auth_dir)}",
    "",
    "api-keys:",
]
lines.extend(f"  - {json.dumps(key)}" for key in api_keys)
lines.extend(
    [
        "",
        "remote-management:",
        f"  allow-remote: {str(allow_remote).lower()}",
        f"  secret-key: {json.dumps(mgmt_key)}",
        "",
        f"request-retry: {request_retry}",
        "",
        "quota-exceeded:",
        f"  switch-project: {str(switch_project).lower()}",
        f"  switch-preview-model: {str(switch_preview_model).lower()}",
        "",
        "routing:",
        f"  strategy: {json.dumps(routing_strategy)}",
        "",
        f"debug: {str(debug_enabled).lower()}",
        "",
    ]
)

with open(config_path, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines))
PY
}

sync_runtime_config() {
    export CONFIG_PATH AUTH_DIR PORT_VALUE
    python3 - <<'PY'
import json
import os
import re

config_path = os.environ["CONFIG_PATH"]
auth_dir = os.environ["AUTH_DIR"]
port = int(os.environ["PORT_VALUE"])

if not os.path.exists(config_path):
    raise SystemExit(0)

with open(config_path, "r", encoding="utf-8") as handle:
    text = handle.read()

updated = text

port_pattern = re.compile(r"(?m)^port:\s*.*$")
auth_pattern = re.compile(r'(?m)^auth-dir:\s*.*$')

port_line = f"port: {port}"
auth_line = f"auth-dir: {json.dumps(auth_dir)}"

if port_pattern.search(updated):
    updated = port_pattern.sub(port_line, updated, count=1)
else:
    updated = port_line + "\n" + updated

if auth_pattern.search(updated):
    updated = auth_pattern.sub(auth_line, updated, count=1)
else:
    updated = updated.rstrip() + "\n" + auth_line + "\n"

if updated != text:
    with open(config_path, "w", encoding="utf-8") as handle:
        handle.write(updated)
PY
}

import_tokens() {
    export AUTH_DIR ZHUCEJI_URL
    python3 - <<'PY'
import json
import os
import sys
import urllib.error
import urllib.request

auth_dir = os.environ["AUTH_DIR"]
base_url = os.environ.get("ZHUCEJI_URL", "").strip().rstrip("/")
if not base_url:
    print("[entrypoint] Token import skipped: empty ZHUCEJI_URL")
    raise SystemExit(0)

url = base_url + "/api/tokens"
request = urllib.request.Request(
    url,
    headers={
        "User-Agent": "CLIProxyAPI-Railway-Bootstrap",
        "Accept": "application/json",
    },
)

try:
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, ValueError) as exc:
    print(f"[entrypoint] WARNING: token import skipped: {exc}")
    raise SystemExit(0)

tokens = payload.get("tokens", [])
imported = 0
for token in tokens:
    content = token.get("content", {})
    email = str(content.get("email", "")).strip()
    access_token = str(content.get("access_token", "")).strip()
    if not email or not access_token:
        continue
    safe = email.replace("@", "_").replace(".", "_")
    path = os.path.join(auth_dir, f"codex-{safe}.json")
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(content, handle)
    imported += 1

print(f"[entrypoint] Imported {imported} token files into {auth_dir}")
PY
}

if [ ! -f "$CONFIG_PATH" ]; then
    echo "[entrypoint] Bootstrapping Railway config at $CONFIG_PATH"
    render_initial_config
fi

sync_runtime_config

existing_auths=$(find "$AUTH_DIR" -maxdepth 1 -name 'codex-*.json' 2>/dev/null | wc -l | tr -d ' ')
if is_truthy "$AUTO_IMPORT_TOKENS"; then
    if [ "${existing_auths:-0}" -lt "$IMPORT_MIN_EXISTING" ]; then
        echo "[entrypoint] Only $existing_auths auth files found; importing tokens now"
        import_tokens
    else
        echo "[entrypoint] Found $existing_auths auth files; refreshing tokens in background"
        import_tokens &
    fi
else
    echo "[entrypoint] Token auto-import disabled"
fi

if is_truthy "$SKIP_EXEC"; then
    echo "[entrypoint] CLIPROXY_SKIP_EXEC=true, bootstrap complete"
    exit 0
fi

cd "$APP_DIR"
exec ./CLIProxyAPI -config "$CONFIG_PATH"
